services:
  pg:
    image: postgres:17.4-bookworm
    container_name: telemetry-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-telemetry}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - telemetry-network

  telemetry-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-backend
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - telemetry-network



networks:
  telemetry-network:
    driver: bridge

volumes:
  postgres-data: