services:
  pg:
    image: postgres:17.4-bookworm
    container_name: telemetry-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-telemetry}
    env_file:
      - .env      
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - telemetry-network

  redis:
    image: redis:7.4.3-alpine
    container_name: telemetry-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - telemetry-network

  telemetry-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-backend
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8080:8080'  # API 포트 추가
    environment:
      - API_PORT=8080
      - API_ALLOWED_ORIGINS=*
      - API_ENABLE_SWAGGER=true
      - REDIS_ADDRESS=redis:6379
      - REDIS_ENABLE_CACHE=true
      - REDIS_TTL=3600
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - telemetry-network

networks:
  telemetry-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: